### ISSUE TITLE
Math Magician - Functional Component Description

### ISSUE THREAD

**Issue by Johnadibe** [Johnadibe/math-magician#4]
### Math Magician - Description of How I used Functional Component

- Firsly, I created an arrow function named Components and inside it I passed the following objects {total: 0, next: null, operation: null} to the useState(), which is the initial value for the state. I used the array destructuring returned by useState() and get the two elements: state and setState(). I use value to access the state and setState() to update the state.

- Secondly, I created a handleClick function and resultDisplay function. In the handleClick function, I used the imported calculate,js file to calculate the state which was updated using setState() in the component.

- Thirdly, the handleClick function is then passed inside the returned button element during an onClick event.

- Lastly, the created functional components is then exported as default.

It is easy to create and update the state in functional components using the useState() hook. React Hooks enable us to use state in React Function Components using arrow functions.

**Comment by bobb-Rob** [comment]
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Johnadibe, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ Well explained

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
